import { SITE } from '@/config/site.config';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const tildaSans = localFont({
  src: [
    {
      path: '../../public/fonts/TildaSans-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TildaSans-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TildaSans-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TildaSans-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TildaSans-Semibold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TildaSans-Semibold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TildaSans-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/TildaSans-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-tilda-sans',
});

export const metadata: Metadata = {
  title: {
    template: `%s | ${SITE.APP_NAME}`,
    default: '',
  },
  icons: {
    icon: './img/favicon.svg',
  },
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${tildaSans.className} antialiased`}>{children}</body>
    </html>
  );
}
